name: Usarp CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Pull of repository
        run: |
          cd /home/ubuntu/usarp/usarp-backend
          git pull origin main

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Stop and remove old containers
        run: |
          cd /home/ubuntu/usarp/usarp-backend
          docker-compose down
          docker-compose rm -f

      - name: Remove unused data
        run: |
          cd /home/ubuntu/usarp/usarp-backend
          docker system prune -af

      # - name: Pull image from Docker Hub
      #   run: |
      #     docker-compose pull

      - name: Start containers with Docker Compose
        run: |
          cd /home/ubuntu/usarp/usarp-backend
          docker-compose up -d
