name: Usarp CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Stop and remove old containers
        run: |
          docker-compose down
          docker-compose rm -f
          
      - name: Remove unused data
        run: |
          docker system prune -af
          docker volume prune -f

      # - name: Pull image from Docker Hub
      #   run: |
      #     docker-compose pull

      - name: Start containers with Docker Compose
        run: |
          docker-compose up -d
