name: Usarp CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.USERNAME_DOCKER_HUB }} -p ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build docker image
        run: docker build -t usarpback/usarp-tool-backend .

      - name: Publish image to Docker Hub
        run: docker push usarpback/usarp-tool-backend:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Stop and remove old containers
        run: docker-compose down

      - name: Pull image from Docker Hub
        run: docker pull usarpback/usarp-tool-backend:latest

      - name: Start containers with Docker Compose
        run: docker-compose up -d
